with wrapper as (

with items as (with itemoption1 as (select io.item_id, io.option_group_id, og.name as option_group_name, io.display_level from ecommerce.item_option as io, ecommerce.option_group as og where io.option_group_id = og.option_group_id and io.display_level = 1),
itemoption2 as (select io.item_id, io.option_group_id, og.name as option_group_name, io.display_level from ecommerce.item_option as io, ecommerce.option_group as og where io.option_group_id = og.option_group_id and io.display_level = 2),
itemoption3 as (select io.item_id, io.option_group_id, og.name as option_group_name, io.display_level from ecommerce.item_option as io, ecommerce.option_group as og where io.option_group_id = og.option_group_id and io.display_level = 3)
SELECT i.item_id::text as data, ''::text as handle, i.name::varchar as title, i.itemdescription as body, v.name::varchar as vendor, ''::text as type, ''::text as tags, FALSE as published, io1.option_group_name as option1name, ''::varchar as option1value, io2.option_group_name as option2name, ''::varchar as option2value, io3.option_group_name as option3name, ''::varchar as option3value, ''::text as variantsku, ''::varchar as variantgrams, ''::text as variantinventorytracker, ''::text as variantinventoryquantity, 'deny'::varchar as variantinventorypolicy, ''::text as variantfulfillmentservice, pr.customerprice::varchar as price, ''::varchar as variantcompareatprice, true as variantrequiresshipping, (CASE WHEN i.itembitmask & 1 = 1 THEN FALSE ELSE TRUE END) as varianttaxable, ''::text as variantbarcode, ''::text as imagesrc, ''::text as imagealttext, ''::text as giftcard, ''::text as seotitle, ''::text as seodescription, ''::text as googleproductcategory, ''::text as googlegender, ''::text as googleagegroup, ''::text as googlempn, ''::text as googleadwordsgrouping, ''::text as googleadwordslabels, ''::text as googlecondition, ''::text as googlecustomproduct, ''::text as googlecustomlabel0, ''::text as googlecustomlabel1, ''::text as googlecustomlabel2, ''::text as googlecustomlabel3, ''::text as googlecustomlabel4, ''::text as variantimage, ''::text as variantweightunit, tx.tax_code as varianttaxcode 
from ecommerce.item as i LEFT OUTER JOIN itemoption1 as io1 ON i.item_id = io1.item_id LEFT OUTER JOIN itemoption2 as io2 ON i.item_id = io2.item_id LEFT OUTER JOIN itemoption3 as io3 ON i.item_id = io3.item_id, ecommerce.vendor as v, ecommerce.price as pr, ecommerce.tax_category as tx
where i.vendor_id = v.vendor_id and i.item_id = pr.source_id and i.primarycategory_id = tx.tax_category_id and pr.sourceclass_id = 5 and pr.pricetype_id = 1 and pr.active = true
// and (insert other parameters here)
group by i.item_id, i.name, i.itemdescription, v.name, pr.customerprice, io1.option_group_name, io2.option_group_name, io3.option_group_name, tx.tax_code
order by i.item_id asc), 
versions as (
with productversionoption1 as (select pvo.productversion_id, o.name as option_name from ecommerce.rsproductversionoption as pvo, ecommerce.option_group as og, ecommerce.rsproductoption as o, ecommerce.item as i, ecommerce.productversion as pv, ecommerce.item_option as io where pvo.productversion_id = pv.productversion_id and pvo.option_id = o.oid and o.group_id = og.option_group_id and pv.item_id = i.item_id and i.item_id = io.item_id and io.display_level = 1), 
productversionoption2 as (select pvo.productversion_id, o.name as option_name from ecommerce.rsproductversionoption as pvo, ecommerce.option_group as og, ecommerce.rsproductoption as o, ecommerce.item as i, ecommerce.productversion as pv, ecommerce.item_option as io where pvo.productversion_id = pv.productversion_id and pvo.option_id = o.oid and o.group_id = og.option_group_id and pv.item_id = i.item_id and i.item_id = io.item_id and io.display_level = 2),  
productversionoption3 as (select pvo.productversion_id, o.name as option_name from ecommerce.rsproductversionoption as pvo, ecommerce.option_group as og, ecommerce.rsproductoption as o, ecommerce.item as i, ecommerce.productversion as pv, ecommerce.item_option as io where pvo.productversion_id = pv.productversion_id and pvo.option_id = o.oid and o.group_id = og.option_group_id and pv.item_id = i.item_id and i.item_id = io.item_id and io.display_level = 3),
versionprice as (select pv.productversion_id, pr.customerprice from ecommerce.productversion as pv, ecommerce.price as pr where pv.productversion_id = pr.source_id and pr.sourceclass_id = 9 and pr.pricetype_id = 1 and pr.active = true )
select pv.item_id || '-' || pv.productversion_id as data, ''::text as handle, ''::varchar as title, ''::text as body, ''::varchar as vendor, ''::text as type, ''::text as tags, FALSE as published, ''::varchar as option1name, pvo1.option_name as option1value, ''::varchar as option2name, pvo2.option_name as option2value, ''::varchar as option3name, pvo3.option_name as option3value, pv.productversion_id::text as variantsku, ''::varchar as variantgrams, ''::text as variantinventorytracker, ''::text as variantinventoryquantity, 'deny'::varchar as variantinventorypolicy, ''::text as variantfulfillmentservice, versprice.customerprice::varchar as price, ''::varchar as variantcompareatprice, true as variantrequiresshipping, (CASE WHEN i.itembitmask & 1 = 1 THEN FALSE ELSE TRUE END) as varianttaxable, ''::text as variantbarcode, ''::text as imagesrc, ''::text as imagealttext, ''::text as giftcard, ''::text as seotitle, ''::text as seodescription, ''::text as googleproductcategory, ''::text as googlegender, ''::text as googleagegroup, ''::text as googlempn, ''::text as googleadwordsgrouping, ''::text as googleadwordslabels, ''::text as googlecondition, ''::text as googlecustomproduct, ''::text as googlecustomlabel0, ''::text as googlecustomlabel1, ''::text as googlecustomlabel2, ''::text as googlecustomlabel3, ''::text as googlecustomlabel4, ''::text as variantimage, ''::text as variantweightunit, tx.tax_code as varianttaxcode
from ecommerce.productversion as pv LEFT OUTER JOIN productversionoption1 as pvo1 ON pv.productversion_id = pvo1.productversion_id LEFT OUTER JOIN productversionoption2 as pvo2 ON pv.productversion_id = pvo2.productversion_id LEFT OUTER JOIN productversionoption3 as pvo3 ON pv.productversion_id = pvo3.productversion_id LEFT OUTER JOIN versionprice as versprice ON pv.productversion_id = versprice.productversion_id, ecommerce.item as i, ecommerce.tax_category as tx, ecommerce.price as pr
where pv.item_id = i.item_id and i.primarycategory_id = tx.tax_category_id
// and (insert other parameters here)
group by pv.item_id, pv.productversion_id, pvo1.option_name, pvo2.option_name, pvo3.option_name, i.itembitmask, versprice.customerprice, tx.tax_code
)

select items.data, items.handle, items.title, items.body, items.vendor, items.type, items.tags, items.published, items.option1name, items.option1value, items.option2name, items.option2value, items.option3name, items.option3value, items.variantsku, items.variantgrams, items.variantinventorytracker, items.variantinventoryquantity, items.variantinventorypolicy, items.variantfulfillmentservice, items.price, items.variantcompareatprice, items.variantrequiresshipping, items.varianttaxable, items.variantbarcode, items.imagesrc, items.imagealttext, items.giftcard, items.seotitle, items.seodescription, items.googleproductcategory, items.googlegender, items.googleagegroup, items.googlempn, items.googleadwordsgrouping, items.googleadwordslabels, items.googlecondition, items.googlecustomproduct, items.googlecustomlabel0, items.googlecustomlabel1, items.googlecustomlabel2, items.googlecustomlabel3, items.googlecustomlabel4, items.variantimage, items.variantweightunit, items.varianttaxcode   
from items
where true 
group by items.data, items.handle, items.title, items.body, items.vendor, items.type, items.tags, items.published, items.option1name, items.option1value, items.option2name, items.option2value, items.option3name, items.option3value, items.variantsku, items.variantgrams, items.variantinventorytracker, items.variantinventoryquantity, items.variantinventorypolicy, items.variantfulfillmentservice, items.price, items.variantcompareatprice, items.variantrequiresshipping, items.varianttaxable, items.variantbarcode, items.imagesrc, items.imagealttext, items.giftcard, items.seotitle, items.seodescription, items.googleproductcategory, items.googlegender, items.googleagegroup, items.googlempn, items.googleadwordsgrouping, items.googleadwordslabels, items.googlecondition, items.googlecustomproduct, items.googlecustomlabel0, items.googlecustomlabel1, items.googlecustomlabel2, items.googlecustomlabel3, items.googlecustomlabel4, items.variantimage, items.variantweightunit, items.varianttaxcode   
UNION
select versions.data, versions.handle, versions.title, versions.body, versions.vendor, versions.type, versions.tags, versions.published, versions.option1name, versions.option1value, versions.option2name, versions.option2value, versions.option3name, versions.option3value, versions.variantsku, versions.variantgrams, versions.variantinventorytracker, versions.variantinventoryquantity, versions.variantinventorypolicy, versions.variantfulfillmentservice, versions.price, versions.variantcompareatprice, versions.variantrequiresshipping, versions.varianttaxable, versions.variantbarcode, versions.imagesrc, versions.imagealttext, versions.giftcard, versions.seotitle, versions.seodescription, versions.googleproductcategory, versions.googlegender, versions.googleagegroup, versions.googlempn, versions.googleadwordsgrouping, versions.googleadwordslabels, versions.googlecondition, versions.googlecustomproduct, versions.googlecustomlabel0, versions.googlecustomlabel1, versions.googlecustomlabel2, versions.googlecustomlabel3, versions.googlecustomlabel4, versions.variantimage, versions.variantweightunit, versions.varianttaxcode   
from versions
where true 
group by versions.data, versions.handle, versions.title, versions.body, versions.vendor, versions.type, versions.tags, versions.published, versions.option1name, versions.option1value, versions.option2name, versions.option2value, versions.option3name, versions.option3value, versions.variantsku, versions.variantgrams, versions.variantinventorytracker, versions.variantinventoryquantity, versions.variantinventorypolicy, versions.variantfulfillmentservice, versions.price, versions.variantcompareatprice, versions.variantrequiresshipping, versions.varianttaxable, versions.variantbarcode, versions.imagesrc, versions.imagealttext, versions.giftcard, versions.seotitle, versions.seodescription, versions.googleproductcategory, versions.googlegender, versions.googleagegroup, versions.googlempn, versions.googleadwordsgrouping, versions.googleadwordslabels, versions.googlecondition, versions.googlecustomproduct, versions.googlecustomlabel0, versions.googlecustomlabel1, versions.googlecustomlabel2, versions.googlecustomlabel3, versions.googlecustomlabel4, versions.variantimage, versions.variantweightunit, versions.varianttaxcode   
)

select wrapper.data, wrapper.handle, wrapper.title, wrapper.body, wrapper.vendor, wrapper.type, wrapper.tags, wrapper.published, wrapper.option1name, wrapper.option1value, wrapper.option2name, wrapper.option2value, wrapper.option3name, wrapper.option3value, wrapper.variantsku, wrapper.variantgrams, wrapper.variantinventorytracker, wrapper.variantinventoryquantity, wrapper.variantinventorypolicy, wrapper.variantfulfillmentservice, wrapper.price, wrapper.variantcompareatprice, wrapper.variantrequiresshipping, wrapper.varianttaxable, wrapper.variantbarcode, wrapper.imagesrc, wrapper.imagealttext, wrapper.giftcard, wrapper.seotitle, wrapper.seodescription, wrapper.googleproductcategory, wrapper.googlegender, wrapper.googleagegroup, wrapper.googlempn, wrapper.googleadwordsgrouping, wrapper.googleadwordslabels, wrapper.googlecondition, wrapper.googlecustomproduct, wrapper.googlecustomlabel0, wrapper.googlecustomlabel1, wrapper.googlecustomlabel2, wrapper.googlecustomlabel3, wrapper.googlecustomlabel4, wrapper.variantimage, wrapper.variantweightunit, wrapper.varianttaxcode
from wrapper
where true
group by wrapper.data, wrapper.handle, wrapper.title, wrapper.body, wrapper.vendor, wrapper.type, wrapper.tags, wrapper.published, wrapper.option1name, wrapper.option1value, wrapper.option2name, wrapper.option2value, wrapper.option3name, wrapper.option3value, wrapper.variantsku, wrapper.variantgrams, wrapper.variantinventorytracker, wrapper.variantinventoryquantity, wrapper.variantinventorypolicy, wrapper.variantfulfillmentservice, wrapper.price, wrapper.variantcompareatprice, wrapper.variantrequiresshipping, wrapper.varianttaxable, wrapper.variantbarcode, wrapper.imagesrc, wrapper.imagealttext, wrapper.giftcard, wrapper.seotitle, wrapper.seodescription, wrapper.googleproductcategory, wrapper.googlegender, wrapper.googleagegroup, wrapper.googlempn, wrapper.googleadwordsgrouping, wrapper.googleadwordslabels, wrapper.googlecondition, wrapper.googlecustomproduct, wrapper.googlecustomlabel0, wrapper.googlecustomlabel1, wrapper.googlecustomlabel2, wrapper.googlecustomlabel3, wrapper.googlecustomlabel4, wrapper.variantimage, wrapper.variantweightunit, wrapper.varianttaxcode
order by wrapper.data asc
